### ISSUE TITLE
"SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode" error encountered

### ISSUE THREAD

**Issue by robertsky** [jksolbakken/linkfollower#1]
I have encountered the following error on Windows 10:

```
let link = process.argv[2];
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
```

![image](https://user-images.githubusercontent.com/1820367/33302416-d2f0c532-d436-11e7-8ed1-b76d9b1e9ca4.png)

**Comment by robertsky** [comment]
minutes after opening this issue, i realised that I was using an extremely old node version.
